In [1]:
import pandas as pd

In [ ]:
# Задание 1

In [2]:
ratings = pd.read_csv('ratings.csv')

In [3]:
def somefoo(x):
    if x <= 2:
        return 'Low'
    elif x <= 4:
        return 'medium'
    elif x == 4.5 or x == 5:
        return 'high'

In [4]:
ratings['class'] = ratings['rating'].apply(somefoo)
ratings.head(10)

   userId  movieId  rating  timestamp   class
0       1        1     4.0  964982703  medium
1       1        3     4.0  964981247  medium
2       1        6     4.0  964982224  medium
3       1       47     5.0  964983815    high
4       1       50     5.0  964982931    high
5       1       70     3.0  964982400  medium
6       1      101     5.0  964980868    high
7       1      110     4.0  964982176  medium
8       1      151     5.0  964984041    high
9       1      157     5.0  964984100    high

In [ ]:
# Задание 2

In [5]:
def foo2(x):
    if 'москв' in x or 'тула' in x or 'ярославл' in x:
        return 'Центр'
    elif 'петербург' in x or 'псков' in x or 'мурманск' in x:
        return 'Северо-Запад'
    elif 'владивосток' in x or 'сахалин' in x or 'хабаровск' in x:
        return 'Дальний Восток'
    else:
        return 'undefind'

In [6]:
keywords = pd.read_csv('keywords.csv')

In [7]:
keywords['region'] = keywords['keyword'].apply(foo2)
keywords.sort_values(by=['region'], ascending = 0)

                                                 keyword   shows    region
45110                мерседес официальный дилер в москве    8543     Центр
38348                               температура в москве   10764     Центр
58158                                      театры москвы    5990     Центр
7446               скидки и акции в супермаркетах москвы   35978     Центр
53320  тарифы на электроэнергию в москве с 1 января 2...    6577     Центр
68005                                   гостиница москва    5651     Центр
92635                      запись к врачу тула доктор 71    3939     Центр
11385  купить квартиру в москве вторичное жилье недорого   24806     Центр
27751  вклады в банках москвы под максимальный процен...   11804     Центр
85584                                    москва панорама    4396     Центр
93948               скидка онлайн в супермаркетах москвы    3902     Центр
18329                      cian ru недвижимость в москве   16603     Центр
5324                                   вакансии в москве   46893     Центр
48534                               сайт госуслуг москвы    7074     Центр
40353                               правительство москвы    8326     Центр
42994                                      днс ярославль    7911     Центр
19612                     киа официальный дилер в москве   19299     Центр
78810                         мрт в москве адреса и цены    4555     Центр
15186                                   госпортал москвы   19425     Центр
849                                      авито ярославль  209581     Центр
81872  ауто ру москва и московская область авто с про...    4394     Центр
49446                                        герб москвы    6934     Центр
84433                               аренда авто в москве    4292     Центр
78815           акции и скидки в супермаркетах ярославля    6723     Центр
42312                                       новая москва    8025     Центр
78820  садовод рынок москва цены на товары каталог 20...    4511     Центр
18306     аптеки столички москвы наличие лекарств и цены   16549     Центр
60095                                         геи москвы    5804     Центр
6093                        авито москва авто с пробегом   74402     Центр
30402  программа передач на сегодня все каналы москва...   11369     Центр
...                                                  ...     ...       ...
33492                      подписчики в реальном времени    9904  undefind
33491                                   программа на стс   10331  undefind
33490                                       доверенность    9822  undefind
33489                                         сберонлайн    9823  undefind
33488                                  жмурки фильм 2005    9826  undefind
33508                                  порно зрелые дамы   14452  undefind
33510  фантастические твари и где они обитают фильм 2...    9823  undefind
33532                                     високосный год    9874  undefind
33522       шторы для зала фото дизайн 2016 года новинки    9923  undefind
33531                                             лагерь    9810  undefind
33530                                           коинс ап    9828  undefind
33529               ответы на сканворды в одноклассниках    9803  undefind
33528                      секс видео смотреть бесплатно   17441  undefind
33527                                               crmp    9811  undefind
33526                                     объяснительная    9811  undefind
33525                                      млекопитающие    9811  undefind
33524                                          антиагент    9812  undefind
33523                                              лобок    9812  undefind
33521              алгебра 8 класс макарычев учебник гдз    9917  undefind
33511    трансформеры 5 последний рыцарь мультфильм 2017    9816  undefind
33520                       поймай толстуху если сможешь    9939  undefind
33519                                           страница    9813  undefind
33518                                   александр семчев   10044  undefind
33517                 сонник толкователь снов посмотреть    9854  undefind
33516                                               мышь    9814  undefind
33515                              язва желудка симптомы    9905  undefind
33514                                       конан варвар    9851  undefind
33513                                           столбняк    9815  undefind
33512                                             багира    9815  undefind
99999                                               ггму    3630  undefind

[100000 rows x 3 columns]

In [ ]:
# Задание 3

In [8]:
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
df = ratings.merge(movies, left_on = 'movieId', right_on = 'movieId')
df = df.groupby('title').mean()[['rating']]
df = df.reset_index()

In [9]:
years = list(range (1950, 2011))

In [10]:
def production_year(x):
    for year in years:
        if str(year) in x:
            return year
    return 1900

In [11]:
df['year'] = df['title'].apply(production_year)
df_sorted = df.groupby('year').mean().sort_values(by=['rating'], ascending = 0)
df_sorted

        rating
year
1971  3.811243
1957  3.767680
1951  3.718044
1952  3.700104
1955  3.672863
1958  3.668078
1976  3.658863
1961  3.656946
1972  3.645005
1968  3.637633
1969  3.635484
1966  3.633244
1970  3.626124
1953  3.586757
1964  3.576297
1963  3.545883
1974  3.522378
1973  3.515731
1954  3.511014
1950  3.501464
1975  3.498999
1962  3.463814
1981  3.415778
1967  3.415113
1959  3.411225
1960  3.405909
1965  3.375767
1979  3.364606
2010  3.346164
2009  3.334304
...        ...
1978  3.296054
1980  3.289612
2008  3.283536
1977  3.278983
1956  3.278093
1982  3.277632
2006  3.272408
1900  3.271038
1999  3.262180
1983  3.254572
2001  3.245998
2000  3.224371
1984  3.222495
2003  3.220392
1996  3.211565
2002  3.200503
2005  3.194514
1986  3.192035
1995  3.176611
1997  3.167504
1993  3.159377
1985  3.154018
1998  3.142272
1990  3.108909
1994  3.096696
1992  3.082417
1988  3.067250
1989  3.045879
1987  3.041854
1991  3.030564

[62 rows x 1 columns]